image:
  pullPolicy: Always
  repository: xerofuzzion/go-ffmpeg-worker
  tag: "1.0.4"

appVolumeMounts:
  data:
    datasetName: "ix-ffmpeg_worker_data"
    mountPath: "/data/db"

lengthOfSegment: "15"
hostNetwork: false
ffmpegWorkerServiceHttpPort: 32500
ffmpegWorkerServiceGrpcPort: 32400

service:
  mongodb:
    enabled: true
    primary: true
    type: NodePort
    targetSelector: "ffmpeg-worker"
    ports:
      manage-http:
        enabled: true
        primary: true
        port: '{{ ( .Values.ffmpegWorkerServiceHttpPort | default 32500 ) }}'
        nodePort: '{{ ( .Values.ffmpegWorkerServiceHttpPort | default 32500 ) }}'
        targetSelector: "ffmpeg-worker"
      manage-grpc:
        enabled: true
        port: '{{ ( .Values.ffmpegWorkerServiceGrpcPort | default 32400 ) }}'
        nodePort: '{{ ( .Values.ffmpegWorkerServiceGrpcPort | default 32400 ) }}'
        targetSelector: "ffmpeg-worker"