{{- include "ix.v1.common.loader.init" . -}}


{{/* Make sure there are not any YAML errors */}}
{{- include "ix.v1.common.values.validate" .Values -}}

---
apiVersion: v1
kind: Secret
metadata:
  # Note how the Secret is named
  name: ffmpeg-worker-secrets
type: Opaque
stringData:
  rtspConnectionUrl: {{ .Values.rtspConnectionUrl }}
  databaseConnectionString: {{ .Values.databaseConnectionString }}

{{ include "ffmpegworker.portal" $ -}}

{{ include "ix.v1.common.spawner.service" $ -}}

---
{{ include "common.storage.hostPathValidate" .Values }}
{{ include "common.deployment.common_config" . | nindent 0 }}
spec: {{ include "common.deployment.common_spec" . | nindent 2 }}
  template: {{ include "common.deployment.pod.metadata" . | nindent 4 }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
    {{- if .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
    {{- end }}
      hostname: {{ template "common.names.fullname" . }}
      {{- if hasKey .Values "global" }}
        {{- if hasKey .Values.global "ixChartContext" }}
          {{- if .Values.global.ixChartContext.addNvidiaRuntimeClass }}
      runtimeClassName: {{ .Values.global.ixChartContext.nvidiaRuntimeClassName }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{ include "common.resources.limitation" . | nindent 10 }}
          {{ include "common.containers.imageConfig" .Values.image | nindent 10 }}
          volumeMounts: {{ include "common.storage.configureAppVolumeMountsInContainer" .Values | nindent 12 }}
            {{ range $index, $hostPathConfiguration := .Values.extraAppVolumeMounts }}
            - name: extrappvolume-{{ $index }}
              mountPath: {{ $hostPathConfiguration.mountPath }}
              {{ if $hostPathConfiguration.readOnly }}
              readOnly: {{ $hostPathConfiguration.readOnly }}
              {{ end }}
            {{ end }}
          ports:
          - name: "grpc-tcp"
            protocol: TCP
            containerPort: {{ .Values.ffmpegWorkerServiceGrpcPort | quote }}
            hostPort: null
          - name: "grpc-udp"
            protocol: UDP
            containerPort: {{ .Values.ffmpegWorkerServiceGrpcPort | quote }}
            hostPort: null
          - name: "http"
            protocol: TCP
            containerPort: {{ .Values.ffmpegWorkerServiceHttpPort | quote }}
            hostPort: null
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RtspConnectionUrl
              valueFrom:
                secretKeyRef:
                  name: ffmpeg-worker-secrets
                  key: rtspConnectionUrl
            - name: ConnStr
              valueFrom:
                secretKeyRef:
                  name: ffmpeg-worker-secrets
                  key: databaseConnectionString
            {{ $envList := (default list .Values.environmentVariables) }}
            {{ if and .Values.gpuConfiguration (hasKey .Values.gpuConfiguration "nvidia.com/gpu") (gt (get .Values.gpuConfiguration "nvidia.com/gpu" | toDecimal) 0) }}
            {{ $envList = mustAppend $envList (dict "name" "NVIDIA_DRIVER_CAPABILITIES" "value" "all") }}
            {{ end }}
            {{ $envList = mustAppend $envList (dict "name" "CameraName" "value" .Values.cameraName) }}
            {{ $envList = mustAppend $envList (dict "name" "HttpPort" "value" .Values.ffmpegWorkerServiceHttpPort) }}
            {{ $envList = mustAppend $envList (dict "name" "GrpcPort" "value" .Values.ffmpegWorkerServiceGrpcPort) }}
            {{ include "common.containers.environmentVariables" (dict "environmentVariables" $envList) | nindent 12 }}
          readinessProbe:
            httpGet:
              port: "http"
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 2
          livenessProbe:
            httpGet:
              port: "http"
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              port: "http"
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 60
            successThreshold: 1
      {{ include "common.networking.dnsConfiguration" .Values | nindent 6 }}
      volumes: {{ include "common.storage.configureAppVolumes" .Values | nindent 8 }}
        {{ range $index, $hostPathConfiguration := .Values.extraAppVolumeMounts }}
        - name: extrappvolume-{{ $index }}
          hostPath:
            path: {{ $hostPathConfiguration.hostPath }}
        {{ end }}
